### ISSUE TITLE
Keine Daten

### ISSUE THREAD

**Issue by WILHER** [gickowtf/enpal-homeassistant#5]
Ich bin neu in HA und habe seit einem Jahr eine ENPAL PV Anlage, nun wollte ich diese mit HA überwache und visualisieren.

Die Installation der Integration hat auch funktioniert, ENPAL hat mir die Zugangsdaten zur InfluxDB geliefert, aber leider bekomme ich keine Daten.

Im Debug-Log steht folgendes:

2023-12-06 07:50:00.600 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up enpal platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/enpal/sensor.py", line 57, in async_setup_entry
    tables = await hass.async_add_executor_job(get_tables, config['enpal_host_ip'], config['enpal_host_port'], config['enpal_token'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enpal/sensor.py", line 31, in get_tables
    tables = query_api.query(query)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/client/query_api.py", line 100, in query
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/service/query_service.py", line 258, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/service/query_service.py", line 338, in post_query_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/api_client.py", line 171, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/api_client.py", line 386, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/rest.py", line 304, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb_client/rest.py", line 254, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'Vary': 'Accept-Encoding', 'X-Platform-Error-Code': 'invalid', 'Date': 'Wed, 06 Dec 2023 06:50:00 GMT', 'Content-Length': '99'})
HTTP response body: b'{"code":"invalid","message":"failed to decode request body: organization name \\"enpal\\" not found"}'

2023-12-06 07:50:01.942 ERROR (SyncWorker_9) [root] Modbus read error at address=33412: Exception Response(131, 3, IllegalAddress)

Kann mir jemand sagen wo ggf. das Problem liegt?

**Comment by OlwinFroon** [comment]
Es fängt damit an, dass es ZWEI Version der Enpal Home Box gibt. Eine (ziemlich hässliche) graue mit einer älteren Softwareversion und neue (etwas elegantere) weiße, mit der neueren Softwareversion.

Die Integration für die alte Box findet sich [hier](https://github.com/Skipperro/enpal-homeassistant).

Wenn Du eine neue Box hast, bist Du hier prinzipiell richtig.
